script:
  - bundle
  - bundle exec rspec
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    on_success: always
    on_failure: always